### ISSUE TITLE
pyqt5について

### ISSUE THREAD

**Issue by pacificbelt30** [Fukuda-B/Team7#1]
PyQt5 is licensed under the GPL, and there is another Qt library for Python, PySide2, licensed under the LGPL. I thought PySide2 was better because it has almost the same functionality and is an official Qt something.

**Comment by Fukuda-B** [comment]
Thanks for the pertinent advice. I'm not very familiar with the license, but I'll change it to make it under the relatively friendly LGPL PySide2 (Qt for python).
